### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Kureev** [Kureev/react-native-side-menu#1]
- [x] Make a working alpha version
- [x] Make an example and description for alpha
- [x] Expose menu API for menu view
- [x] Support different animations
- [x] Toggle menu functionality (thanks, @dvcrn)
- [x] Extend and describe side menu API
- [x] Create `menuPosition` property in cases of using menu on the right side (will be opened by slide right-to-left)

**Comment by adrian-social-prod** [comment]
Nice plugin. Is there a way to trigger openMenu externally?

**Comment by Kureev** [comment]
Thanks for the warm words! I'm thinking about it now, but it doesn't seems to be an easy solution. You need to render menu first to get a reference to it's instance. Since you have a ref, you can call `openMenu`. I'll try to make an example for that tomorrow.

**Comment by adrian-social-prod** [comment]
Yes this.refs.{menuid}.openMenu() works fine. thanks

**Comment by chirag04** [comment]
@Kureev Can you put up a small example for this? I need to trigger openMenu externally.

Not sure how to handle the ref thing.

**Comment by Kureev** [comment]
Sure, I'll try to make an example asap, but I need some time to figure out about #4

**Comment by chirag04** [comment]
Thanks. I would need #4 to be solved anyways. I will also look into the codebase in some time.

**Comment by swennemans** [comment]
@chirag04 landed in this thread to trigger the openMenu from a button. Not sure if this is what you want, but just in case here is a gist: https://gist.github.com/swennemans/fdaa321fcc02db96de96

**Comment by chirag04** [comment]
@swennemans Awesome thanks. I would prefer an api exposed by the component itself for this though.

**Comment by Kureev** [comment]
@chirag04 @adrian-social-prod `open` method has been exposed in `0.3.0` (thanks to @dvcrn)

**Comment by liubko** [comment]
property to open menu from the right side will be super usefull

**Comment by Kureev** [comment]
@liubko you mean API to toggle menu? It's already implemented. See #15

**Comment by liubko** [comment]
1. @Kureev no, I mean: ability to position drawer at the right side of the screen

2. what do you think about adding dragElement like here: http://jakiestfu.github.io/Snap.js/demo/apps/dragElement.html
because currently SideMenu's responder handles **all** drag events on the screen, and it breaks my apps functionality.

**Comment by Kureev** [comment]
@liubko Ah, I see:
- Yes, it's in the roadmap. Unfortunately, I'm busy last month to implement something new, but in theory nothing hard.

- I think it's a really great idea. I think instead of creating additional layer we can add prop with ref to handler:
  ```javascript
  <SideMenu handler={'handler'} menu={<Menu/>}>
    <ListView ref='handler' source={source} />
  </SideMenu>
  ```
